// Deployment variables

const constantes = {
    datosvar: {       
      version: '"version":"5.600.0"',
      email: 'tadera2504@etramay.com',
      ecoemail: 'ecoqa@xxxl.digital',      
      user: 'roberto.tunon@xxxl.digital',
      pwd: 'Duncan21',
      name: 'Roberto',
      surname: 'Tuñon',      
      message: `IT Test. Please ignore it. Thank you!
      IT-Test. Bitte ignorieren Sie ihn. Ich danke Ihnen.
      Test IT. Prosím, ignorujte ho. Děkujeme!`,
      address: "Bahnhofstraße", 
      nummer: "10",
      birthdate: "24.01.1980",      
      Pocoproduct : "498152800",
      SSOuser: "LUTZNT\\ROBE",
      SSOpwd: "Utrecht28#",
      Klarna: "263250",
      Branch: "989d63a46c",
      karte: "2014740137",
      
    },

    datosDE: {        
      Cookiebutton: 'Weiter einkaufen',      
      PostalCode: '10178',
      City: 'Berlin',
      PostalCode2: '77716',
      City2: 'Haslach im Kinzigtal', 
      Product: '8227089202',
      Phone: '030250025',
      Phone2: '017614284340',
      Floor: '1',
      Message: 'Dies ist eine Testbestellung, bitte stornieren und Geld zurücküberweisen. Vielen Danke.',
      MKPProduct: '800000464523',
      MKPPhoneApprove: "+49017614284340",
      MKPPhoneDeny: "+49017610927312",
      FrameNumber: 'Iframe für Kartennummer',
      FrameDate: 'Iframe für Ablaufdatum',
      FrameCVV: 'Iframe für Sicherheitscode',
      BillieUID: 'DE812345678',
      BillieName: 'Zeta Electronics Gold GmbH',
      BillieStreet: 'Tannenweg',
      BillieNumber: '4',
      BilliePostalCode: '77716',
      BillieCity: 'Haslach im Kinzigtal',
      Country: 'DE',
    },

    datosAT: {      
      Cookiebutton: 'Weiter einkaufen',	      
      PostalCode: '4020',
      City: 'Linz', 
      PostalCode2: '1100',
      City2: 'Wien', 
      Product: '3501049101',
      MKPProduct: '800000943827',
      MKPPhoneApprove: "+4306762600456",
      MKPPhoneDeny: "+4306762600745",
      Phone: '050545454',
      Phone2: '06762600456',      
      FrameNumber: 'Iframe for card number',
      FrameDate: 'Iframe for expiry date',
      FrameCVV: 'Iframe for security code',    
      BillieUID: 'ATU65296645',
      BillieName: 'Theta Electronics Gold GmbH',
      BillieStreet: 'Fichtenstraße',
      BillieNumber: '9',
      BilliePostalCode: '6364',
      BillieCity: 'Brixen im Thale',
      Country: 'AT',
    },   

    datosCZ: {      
      Cookiebutton: 'Nakupovat dále',	    
      PostalCode: '102 00',
      City: 'Praha 102',
      Product: '3279063603',
      Phone: '221714714',
      Message: 'Jedná se o testovací objednávku digitálního oddělení XXXLutz. Prosím, zrušte ji a vraťte peníze zpět. Děkujeme za pomoc.',
      FrameNumber: 'Iframe pro číslo karty',
      FrameDate: 'Iframe pro datum vypršení platnosti',
      FrameCVV: 'Iframe pro bezpečnostní kód',
      Country: 'CZ',

    },
  
    datosCH: {      
      Cookiebutton: 'Geht klar!',	
      PostalCode: '8112',
      City: 'Otelfingen', 
      Product: '37313811',
      Phone: '442154000',
      FrameNumber: 'Iframe for card number',
      FrameDate: 'Iframe for expiry date',
      FrameCVV: 'Iframe for security code',  
      Country: 'CH',
    },

    datosSE: {      
      Cookiebutton: 'Acceptera alla cookies',	
      PostalCode: '11151',
      City: 'Stockholm', 
      Product: '',
      MKPPhoneApprove: "+46701740615",
      MKPPhoneDeny: "+46701740620",
      Phone: '87005690',
      FrameNumber: 'Iframe för kortnummer',
      FrameDate: 'Iframe för utgångsdatum',
      FrameCVV: 'Iframe för säkerhetskod',
      BillieUID: 'SE999999999901',
      BillieName: 'XXXLutz SE',
      Country: 'SE',
      NINSE: '19410321-9202',      
    },

    datosRO: {      
      Cookiebutton: 'Accept toate cookie-urile',	
      PostalCode: '032604',
      City: 'Bucuresti', 
      Product: '001930000219',
      Phone: '213055500',
      Country: 'RO',
      FrameNumber: 'Iframe pentru numărul cardului',
      FrameDate: 'Iframe pentru data de expirare',
      FrameCVV: 'Iframe pentru codul de securitate',
    },   

    datosRS: {      
      PostalCode: '11426',
      City: 'MELJAK', 
      Product: '000840005101',
      Phone: '112635622',
      Country: 'RS',
    },

    datosSI: {      
      Cookiebutton: 'V redu je!',	
      PostalCode: '1002',
      City: 'Ljubljana', 
      Phone: '013061215',
      FrameNumber: 'Iframe za številko kartice',
      FrameDate: 'Iframe za datum poteka veljavnosti',
      FrameCVV: 'Iframe za varnostno kodo',      
      Country: 'SI',
    },

    datosHR: {      
      PostalCode: '10010',
      City: 'Zagreb-Slobostina', 
      Product: '',
      Phone: '14898555',
      FrameNumber: 'Iframe za broj kartice',
      FrameDate: 'Iframe za datum isteka',
      FrameCVV: 'Iframe za sigurnosni kôd',  
      Country: 'HR',
    },

    datosSK: {      
      Cookiebutton: '',	
      PostalCode: '81101',
      City: 'Bratislava', 
      Product: '',
      Phone: '0918573172',
      FrameNumber: 'Iframe pre číslo karty',
      FrameDate: 'Iframe pre deň vypršania platnosti',
      FrameCVV: 'Iframe pre bezpečnostný kód',  
      Country: 'SK',
    },

    datosHU: {      
      Cookiebutton: 'Összes süti elfogadása',	
      PostalCode: '1052',
      City: 'Budapest V.', 
      Product: '',
      Phone: '0614388080',
      FrameNumber: 'Iframe a kártyaszámhoz',
      FrameDate: 'Iframe a lejárati dátumhoz',
      FrameCVV: 'Iframe a biztonsági kódhoz',  
      Country: 'HU',
    },


    PayLive: {      
      cardnumber: "5319 5447 7987 5501",
      cardholder: "Mike Pascher",
      cardcvv: "311",
      carddate: "04/27",
      PayPalusr: "mp2@xxxlutz.at",
      PayPalpwd: "0810Shadow",
    },

    PayQC: {      
      PayPalusr: "too-buyer@xxxlutz.at",
      PayPalpwd: "xxxlutz12345",
      cardnumber: "5555 4444 3333 1111",
      visanumber: "4646 4646 4646 4644",
      threedsnumber: "5454 5454 5454 5454",
      cardholder: "Robert Tunon",
      cardcvv: "737",
      carddate: "03/30",
    }

};

module.exports = constantes;
  
